version: '2'

services:
  deliveryservice:
    environment:
      - apiurl=https://api.telegram.org/bot
      - tokenapi=348485796:AAEEPGXp76GT8n--KKyHBS0tJEetOVSMF5o
      - connectionString=amqp://user:password@rabbitmq
      - exchange=pv.telegram.message
      - routingkey=telegram
    image: deliveryservice
    build:
      context: ./publish/DeliveryService
      dockerfile: dockerfile
    networks:
      - rabbitmq
  commander:
    image: commander
    build:
      context: ./publish/Commander
      dockerfile: dockerfile
    networks:
      - rabbitmq
    volumes:
      - data-volume:/app/data/commander
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
      - 15671:15671
    networks:
      - rabbitmq
    environment: 
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

networks:
  rabbitmq:
    driver: bridge

volumes:
  data-volume:
